# Generated by Django 4.1.7 on 2023-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
