# Generated by Django 4.1.7 on 2023-03-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='type_of_service',
        ),
    ]
