# Generated by Django 4.1.7 on 2023-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('job_descrition', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'job_category',
                'verbose_name_plural': 'job_categories',
            },
        ),
    ]
