# Generated by Django 4.1.7 on 2023-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/team')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
