# Generated by Django 4.1.7 on 2023-03-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
    ]
